apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-07-08T08:31:16Z"
  labels:
    run: nginx
  name: nginx
  namespace: opa
  resourceVersion: "9621"
  selfLink: /api/v1/namespaces/opa/pods/nginx
  uid: c4344b8b-1a2d-4612-93cd-09c70aae283e
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hq7bq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-hq7bq
    secret:
      defaultMode: 420
      secretName: default-token-hq7bq
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-07-08T08:31:16Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-07-08T08:31:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-07-08T08:31:20Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-07-08T08:31:16Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c057d86a1f6c0811c05b3280c5a08459e9aff5944d4488852fb2192653c2cb19
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:96fb261b66270b900ea5a2c17a26abbfabe95506e73c3a3c65869a6dbe83223a
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-07-08T08:31:19Z"
  hostIP: 192.168.64.21
  phase: Running
  podIP: 172.17.0.7
  qosClass: BestEffort
  startTime: "2019-07-08T08:31:16Z"
